<template>
    <v-app>
     <v-container>
       <h1 class="text-center mb-5 primary rounded py-5 white--text">Blog</h1>
       <v-card class="rounded mb-6" v-for="post in posts" :key="post.date">
         <v-card-title>
           <v-avatar color="primary" class="white--text mx-3">M</v-avatar>
           Mohammad Al-Mahmoud
           <v-spacer></v-spacer>
           <p class="grey--text text-caption"><v-icon>mdi-clock</v-icon>{{post.date}}</p>
         </v-card-title>
         <v-card-text class="px-10" style="line-height: 30px!important;">
          <h2 class="mb-10 mt-5">{{post.title}}</h2>
           {{post.text}}
         </v-card-text>
         <v-card-actions>
           <v-chip class="mx-5"><v-btn text><v-icon class="mr-2">mdi-thumb-up-outline</v-icon> 40</v-btn></v-chip>
           <v-chip><v-btn text><v-icon class="mr-2">mdi-message-outline</v-icon> 23</v-btn></v-chip>
         </v-card-actions>
       </v-card>
     </v-container>
    </v-app>
</template>
<script>
  export  default {
    name:'blog-component',
    data(){
      return{
        posts:[
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          }, {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },
          {
            title:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam consequatur eum, magnam necessitatibus rerum sit?',
            text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur excepturi inventore minus odit officia ratione sit ut voluptas voluptate. Est mollitia repellat similique voluptas? A adipisci aliquam aliquid, aperiam assumenda at cupiditate dicta dolore doloremque dolores ducimus earum et, ex excepturi expedita illo impedit ipsam itaque labore laboriosam minima minus mollitia natus nulla officia placeat provident quam quasi quia quis reiciendis rem saepe sed velit voluptatem voluptates voluptatibus? Assumenda, aut dolor ducimus ex excepturi expedita inventore itaque maiores obcaecati, optio quidem reprehenderit sit temporibus! Ad dolorem eius, est facere maxime nemo, nobis possimus reprehenderit sapiente tempora vero, voluptatibus. A ab architecto aut consequuntur dolor eaque eos excepturi facere fugiat fugit hic, illum laudantium magnam molestias necessitatibus nihil non officiis possimus quae quidem quis repellendus saepe sint temporibus unde vel veniam vero, voluptate voluptates voluptatibus. Aut corporis deleniti eveniet, ipsam iure mollitia nihil optio quos reprehenderit repudiandae, tempora voluptatem! Architecto commodi eaque explicabo harum laboriosam nam porro voluptas voluptatem. Aliquid amet aspernatur at cum cumque delectus deserunt dicta dolore doloremque ducimus, ea ex facere facilis fugiat illum incidunt iste libero magni maiores minus modi molestias nam natus neque nesciunt non nostrum, numquam odit quia quis, quo recusandae sequi tempora tempore tenetur voluptas voluptatum! Eius nisi obcaecati sint voluptatum! Accusamus amet aspernatur, commodi consequatur ea eos fuga magni nihil quia repudiandae rerum voluptatibus. Alias distinctio excepturi exercitationem ipsam nulla. Aliquam cupiditate doloremque ea et facere iste maxime minus quaerat reiciendis sit. Alias aut autem blanditiis commodi consectetur corporis distinctio doloremque esse eveniet expedita hic impedit in inventore magnam maiores, maxime minima neque optio perspiciatis praesentium quo recusandae sequi soluta tempora ullam voluptatem voluptates voluptatibus. Asperiores atque cumque deleniti exercitationem modi provident repellat velit, veritatis! Ab ad aperiam architecto consectetur, consequuntur cumque distinctio in maiores nesciunt quaerat rem repellat soluta. Iure, nesciunt sapiente.',
            date:Date().toString(),
          },



        ]
      };
    },
  }
</script>
<style scoped>

</style>